### PR TITLE
init 2.2.4

### PR DESCRIPTION
**Pull request by felixhao28**
This PR represents ongoing changes in v2.2.4

### CODE REVIEW

**Comment by reagle** [comment]
This is breaks parsing markdown documents for me. In order to deal with YAML front matter, I changed some of the regex's to look for 4 dashes '----' rather than three for under-headings. I see, but haven't yet understood, your changes, but the result doesn't work because of the first line.

screen shot 2017-09-04 at 11 22 21 am

If I remove the first line, the markdown is styled as expected.

**Comment by felixhao28** [comment]
Hi @reagle , I only saw YAML front matter enclosed by two "---"s. You have surrounded it with "---" and "...". Is it a standard usage? I failed to find a specification on YAML front matter. And I think if you change the "..." to "---" everything should work.

**Comment by reagle** [comment]
A YAML block can end in '---' or '...' and I've followed the [pandoc examples](http://pandoc.org/MANUAL.html#extension-yaml_metadata_block) of using the latter.

**Comment by felixhao28** [comment]
@reagle I see. If it's blocking you, you can follow the change from here: 0d535254ad999e7d7e469c6fccf068e7c364bc5e before the next update.

**Pull request merged**
