### PR TITLE
Adding WikiLink functionality

### PR DESCRIPTION
**Pull request by dave-ellis**
This introduces the basic wiki link functionality including:
* Styling and formatting of wiki links
* Key mappings for:
    * Making a wiki link
    * Opening a wiki link page
    * Opening the home page
    * Opening today's journal page
* Configuration settings for wiki links

### CODE REVIEW

**Comment by felixhao28** [comment]
@dave-ellis I reviewed the changes and here are some comments:

1. The shortcut ctrl+alt+d does not seem to work for me (Windows), while the choosing commands from command palette works.
2. I personally think the shortcuts should be disabled in settings by default. Because it will probably not used by the majority of users. Anyone reading this can share your opinions on this.
3. The syntax is defined as [a-zA-Z0-9]+ which means [[SomePage.md]] will not be highlighted (because dot). Is this intentional?
4. What does "open reference" do? What's the meaning of it?
5. "Open page" command actually creates a page if nothing is in selection. You might want to describe this behavior in readme.
6. Open page can be added to [context menu](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/2.2.6/Context.sublime-menu) for easier access.
7. "List back links" should generate an alert (e.g. a message on the left bottom corner/a popup, your choice) if no back links are found. Otherwise it will confuse users.
8. All your TextCommands should inherit from [MDETextCommand](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/2.2.6/mdeutils.py#L12) to prevent them from showing up when the opened document is not markdown.

**Comment by dave-ellis** [comment]
> 1. The shortcut ctrl+alt+d does not seem to work for me (Windows), while the choosing commands from command palette works. I changed to to ctrl+alt+l and then it works. Maybe something is conflicting with ctrl+alt+d but I used sublime.log_commands(True) and nothing showed up.

I agree something on your setup or OS must conflicting.  My choice was of `ctrl+alt+d` was somewhat arbitrary, but I like the fact that it can easily be invoked using one hand.  Let me know if you feel it's necessary to change it to something else.


>  2. I personally think the shortcuts should be disabled in settings by default. Because it will probably not used by the majority of users. Anyone reading this can share your opinions on this.

I have disabled the shortcuts by default for now.  


> 3. The syntax is defined as [a-zA-Z0-9]+ which means [[SomePage.md]] will not be highlighted (because dot). Is this intentional?

Hmm, yes it was.  However, thinking about it, allowing the extension does make it less restrictive, as such it makes sense.  I have committed a change that allows this.


> 4. What does "open reference" do? What's the meaning of it?

The open reference command opens the URL reference under the cursor in the system browser.  This is functionality that I use quite a bit with my personal wiki notes.  


> 5. "Open page" command actually creates a page if nothing is in selection. You might want to describe this behavior in readme.

I have added some details in the readme.


> 6. Open page can be added to context menu for easier access.

Done.  I have added all the wiki commands to the context menu and controlled thier visiblity.


> 7. "List back links" should generate an alert (e.g. a message on the left bottom corner/a popup, your choice) if no back links are found. Otherwise it will confuse users.

Done.  I have added a status message for when there are no backlinks found.

> 8. All your TextCommands should inherit from MDETextCommand to prevent them from showing up when the opened document is not markdown.

Done.

**Comment by felixhao28** [comment]
> The open reference command opens the URL reference under the cursor in the system browser.

Is it different from right click, and open?
image

I will review the other changes this weekend.

**Comment by dave-ellis** [comment]
Nope, it does the same.  Only I couldn't figure out how to tie that command to hot keys.

I would be happy to remove it from this patch as it is kind of separate functionality.

**Comment by felixhao28** [comment]
Yeah let's remove it. I don't think open a URL link requires an additional command.

**Comment by dave-ellis** [comment]
Okay done.  I have removed the open_reference functionality

**Comment by felixhao28** [comment]
Sorry for the delay. One last thing to discuss before merge. Do we really need the journal-related commands and even make keybindings for them? I mainly use MD for the one-page README so I don't quite know how important it is.

**Comment by dave-ellis** [comment]
In theory, it could be separated out into a separate package.  However, this is something that I believe works very well as part of this package.  Additionally it is functionality that I use almost every day.

It is worth noting that a lot of other wiki applications provide journal functionality including VimWiki (a vim extension).

**Comment by felixhao28** [comment]
OK I am merging it.

**Pull request merged**
