### PR TITLE
Reorganize plugins in a dedicated package

### PR DESCRIPTION
**Pull request by deathaxe**
This PR  suggests to move all plugins into a `plugins` sub directory and modify required import statements. ST2 style imports are removed as other changes (`embed` in syntax definitions, ...) of the package break ST2 compatibility anyway.

The main reasons for this change are:

1. Some modules import others (e.g. nearly all import `mdeutils`). 
   As ST handles any top-level python module as independent plugin,
   importing one into another easily creates duplicate instances of
   those modules in python's runtime environment. As a result, reloading
   plugins (during update or development) may easily cause multiple
   instances of the same global object.

   This is no longer the case now.

2. The single `plugin.py` module in package root controls, which
   resources (API classes) are published to ST, so it doesn't need to
   query all modules one after another on its own.

   So we get more control about what ST sees or not.
   
   It hides the base class MDETextCommand for instance, which is of no
   value when called directly, but was registered as valid command
   before this commit.

3. All files are merged and ST just sees a single plugin module it needs
   to interact with, which makes loading/reloading faster.

The following things need to be kept in mind

1. Each command or event listener needs to be imported by plugin.py, 
   which means slightly higher effort when adding API functions.

2. `plugin.py` clears `sys.modules` cache upon import time to make sure
   all modules in the plugins directory are reloaded in correct order.

3. Changes to a module in the plugins sub directory take effect only by
   saving the main `plugin.py` (which causes everything to be reloaded).

### CODE REVIEW

**Comment by felixhao28** [comment]
Can you please also confirm that https://github.com/SublimeText-Markdown/MarkdownEditing/issues/591 is gone? I have been quite occupied recently and mostly switched to VSCode anyways.

And if you are interested, I can add you to the maintainers of MDE. Your recent commits/PRs are of high quality and we can definitely use your help.

**Comment by deathaxe** [comment]
I don't plan to switch to VS Code and have some ideas to improve Mardown Editing experience. I am quite involved in other community activities but I guess can invest some some hours into this package. Already was looking at SmartMarkdown as a base, but this package is far supirior already.

I am interested in helping maintaining the package.

**Comment by felixhao28** [comment]
Sounds great. @ttscoff @maliayas What do you guys think?

**Comment by ttscoff** [comment]
I'm good with it!

**Comment by maliayas** [comment]
Sure Felix, that's our spirit. In the last several years, unfortunately I couldn't find time to join the game.  I'll return someday hopefully.

P.S. Dear Felix, could you please remove my line from the "donations" header? I can re-add it in the future in case I return.

 All the best.

**Comment by felixhao28** [comment]
@deathaxe the invitation is sent. Thank you for keeping this project alive.

**Comment by dreece87** [comment]
What the fuck is all of This?

**Comment by felixhao28** [comment]
@dreece87 I don't know why GitHub sends you emails about this. Please kindly ignore it. Thank you.

**Pull request merged**
