### PR TITLE
Add iA Writer colors and formatting

### PR DESCRIPTION
**Pull request by kevinSuttle**
## Changes
- Include extra headings in GFM tests
- Add spell checking and English Dictionary to `Markdown.sublime-settings` as defaults
- Match iA Writer colors and formatting _(for better or worse)_

## Recommended user settings
```diff
+      "caret_style": "blink",
+      "draw_indent_guides": false,
+      "draw_white_space": "all",
+      "ensure_newline_at_eof_on_save": true,
+      "line_padding_bottom": 8,
+      "line_padding_top": 7,
+      "margin": 10,
+      "scroll_past_end": false,
+      "scroll_speed": 0.8,
+      "trim_trailing_white_space_on_save": true,
+      "use_simple_full_screen": true,
+      "wide_caret": true,
```

### CODE REVIEW

**Comment by felixhao28** [comment]
We are doing development on v2.1.7 branch. Could you change your PR target to v2.1.7 instead?

**Comment by kevinSuttle** [comment]
Sure thing.

**Comment by kevinSuttle** [comment]
Closed in favor of https://github.com/SublimeText-Markdown/MarkdownEditing/pull/343

**Comment by kevinSuttle** [comment]
Added more detail and comments to https://github.com/SublimeText-Markdown/MarkdownEditing/issues/342

**Pull request closed without merging**
