### PR TITLE
Version 2.1.2

### PR DESCRIPTION
**Pull request by maliayas**
This PR represents the ongoing development for the next version (`2.1.2`).

### CODE REVIEW

**Comment by maliayas** [comment]
Felix, what do you think about f2506cd9e8e03efb20996c45f132ee71b0205e3e and 3812b4f885b4d8eb69d368b7b5a5fb893a6aa307?

**Comment by felixhao28** [comment]
Looks reasonable

**Comment by maliayas** [comment]
Is it a right time for a release? What do you think?

**Comment by felixhao28** [comment]
Looks good.

**Pull request merged**
