### PR TITLE
Version 2.1.4

### PR DESCRIPTION
**Pull request by maliayas**
This PR represents the ongoing development for the next version (`2.1.4`).

### CODE REVIEW

**Comment by maliayas** [comment]
Great progress!

**Comment by maliayas** [comment]
@felixhao28 Felix, would you be interested in modifying wrap command based on this style: #301?

I think it will receive quite positive feedback from the users.

**Comment by maliayas** [comment]
Hello @felixhao28. Do you have anything to add for the release? I think we can make a release.

**Comment by felixhao28** [comment]
@maliayas  Sure, go ahead!

**Pull request merged**
