### PR TITLE
Version 2.1.5

### PR DESCRIPTION
**Pull request by maliayas**
This PR represents the ongoing development for the next version (`2.1.5`).

### CODE REVIEW

**Comment by maliayas** [comment]
New "paste as reference" is pretty fine. Multicursor is good idea there. On the other hand, it is similar to "insert reference" command per the job. I think we should combine them in the most simple way possible. Here is what I have come up with. Description is kinda long but I believe usage is more intuitive.

Given below state and there is a URL on the clipboard:

ekran goruntusu 2015 12 16 23_08_42

"Paste as reference" creates this state:

ekran goruntusu 2015 12 16 23_11_19

If the `consectetur` is already taken as a reference name, we maintain a document wide auto generated reference name in the style of `[21]` and use it instead of `consectetur`. `21` will be the smallest untaken number in the document.

If there is not a URL in the clipboard, don't use clipboard at all and create this state:

ekran goruntusu 2015 12 16 23_35_56

Place of the cursor will allow directly entering the URL which I believe is more intuitive than the promp dialog. We can use the string in the clipboard as reference name but I'm not sure this is how people do it. If by doing that we fail most of the time and make the user go back to the reference name and remove the irrelevant text, whole thing becomes meaningless.

***

This approach removes the need of "insert reference" command. We can remove it for simplicity. And in the mean time, we have automatically eliminated the nonfancy "Given ref is already taken" alert by autogenerating.

What do you think?

**Comment by ttscoff** [comment]
For the latter suggested version (no URL on clipboard), the brackets 
following the link in the text should have the 22 in them. The other 
option is to leave those blank, and then use the selected text as the 
title of the reference, e.g.

	Lorem ipsum dolor sit amet, [consectetur][] adipisicing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad 
minim veniam

	[consectetur]:

**Comment by maliayas** [comment]
You are right. We can use `consectetur` if available, if not then `22`. In the second case, as you said, it must be put in the brackets following the link as well.

**Comment by maliayas** [comment]
@felixhao28 Hello Felix. Unfortunately I'm not able to create lesiure time these days for the project. On the other hand, I don't want to block the development. I really appreciate your contribution. So if you wish, you can release your contributions without my review. I can't speak on behalf of @ttscoff however, maybe he can review the process in the meantime.

Soon or later, I'll find time to review things, just can't tell exactly when.

**Comment by felixhao28** [comment]
@maliayas What is your practice to release a new version? I guess:

1. Merge this pull request
2. Rename v2.1.5 branch to v2.1.6
3. Create messages/2.1.6.md
4. Create a pr from v2.1.6 branch to master

Am I missing something?

**Comment by maliayas** [comment]
Yup. Publishing happens when you create `2.1.5` tag. Package Control looks for tags. Also, don't use fast-forward merging, create a merge commit instead. That's it.

**Pull request merged**
