### PR TITLE
Add 3left macros

### PR DESCRIPTION
**Pull request by Kristinita**
Left, left, left. For use with commands `reference_new_inline_link` and `reference_new_inline_image `. Demonstration:

3 left

Thanks.

### CODE REVIEW

**Comment by felixhao28** [comment]
Nice suggestion. I prefer using tab stops:
tab

What is the screen recorder you are using by the way? It looks nice.

**Comment by Kristinita** [comment]
@felixhao28

Also I use AutoHotkey macros for insert links and images.

**Copy link script**: <https://www.pastery.net/vuyhrk/>
**Copy image script**: <https://www.pastery.net/khfvnc/>

Macros for MarkdownEditing

[ScreenToGIF](https://github.com/NickeManarin/ScreenToGif) — programs for screencasts for me.
[KeypressOSD](https://autohotkey.com/boards/viewtopic.php?t=225) — script for displayed keyboard keys and mouse buttons for me.

Thanks.

**Comment by felixhao28** [comment]
Great! Thank you.

**Comment by Kristinita** [comment]
@felixhao28, we need add additional hotkeys, because we don't want move in link use <kbd>Tab</kbd> and <kbd>Shift+Tab</kbd> in list elements:

Link in list

For example, I add in my `User/Default (Windows).sublime-keymap` file these lines:

```json
{ "keys": ["super+ctrl+browser_forward"], "command": "next_field", "context":
    [
        { "key": "has_next_field"}
    ]
},
{ "keys": ["super+ctrl+browser_back"], "command": "prev_field", "context":
    [
        { "key": "has_prev_field"}
    ]
},
```

Thanks.

**Comment by felixhao28** [comment]
Well I think that is just your personal preference. And glad that you found a solution.

**Pull request closed without merging**
